### ISSUE TITLE
optimize

### ISSUE THREAD

**Issue by yangxian** [alantrrs/OpenTLD#12]
I like your work, it is so cool. I think the function "filterPts" don't need to 
check "status" twice and the second check is wrong.
And I find the function TLD::getOverlappingBoxes is not efficient.the nth_element waste much time, and the waste is not necessary.
Best wish~

**Comment by alantrrs** [comment]
Hi, you are completely right about the 'status' issue. Thanks!
How would you replace the nth_element function? I'm using nth_element instead of a full sort of the elements because I think it is faster but if you have any suggestion let me know.

**Comment by yangxian** [comment]
Hi, Thanks for your reply. I think nth_element is fast. But the structure OComparison is a little slow

**Comment by alantrrs** [comment]
Any suggestions to make it faster?

On Thu, Dec 29, 2011 at 6:12 PM, yangxian <
reply@reply.github.com

> wrote:
> 
> Hi, Thanks for your reply. I think nth_element is fast. But the structure
> OComparison is a little slow
> At 2011-12-30 03:43:09,"Alan Torres" reply@reply.github.com wrote:
> 
> > Hi, you are completely right about the 'status' issue. Thanks!
> > How would you replace the nth_element function? I'm using nth_element
> > instead of a full sort of the elements because I think it is faster but if
> > you have any suggestion let me know.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/alantrrs/OpenTLD/issues/12#issuecomment-3304363
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alantrrs/OpenTLD/issues/12#issuecomment-3307049

## 

_Alan I. Torres Nogales_
