### ISSUE TITLE
alternative licence

### ISSUE THREAD

**Issue by liuliu** [alantrrs/OpenTLD#15]
Thanks for the hard work on porting the matlab code over to C++. I intended to port your code to ccv: https://github.com/liuliu/ccv, but find the licence is incompatible, since it is a C++ code without any original matlab code, you can have an alternative licence other than the author's original GPL3, can you add a more liberal licence to your project such as MIT, Apache or FreeBSD licence? Thanks!

**Comment by liuliu** [comment]
instead of port, I rewrote it ;-)

**Comment by alantrrs** [comment]
Just saw your post on HN and reminded me I had to answer this issue. I'm sorry I wasn't able to help. Great work!

**Comment by secutron** [comment]
Professor LiuLiu???
