### ISSUE TITLE
VS2010 & OpenCV crash / cv::Mat_<unsigned>

### ISSUE THREAD

**Issue by rudihh** [alantrrs/OpenTLD#6]
Hi Allan,

I'm using Qt 4.3.7,OpenCV 2.3,MS VS2010

I have a exception in the conversion of the 8Bit B/W-Image to the 32 bit unsigned cvMat.
bool Detector::init(IplImage& image, const QRectF& region)
{
    …
    cv::Mat_<unsigned> imageMat(m_image);  <--- crashes wenn converting the 8 Bit BW-Image to 32 Bit cvMat
                because there is no conversation from CV_8U to CV_32U 
                in modules\core\src\convert.cpp/cv::Mat::convertTo()    

```
cv::Mat_<int> imageMat(m_image);    works, because there is a conversation from CV_8U to CV_32U
```

}
What is wrong with that? I saw another Thread with someone using also OpenCV2.3, without this Problem. 

Cheers
Rudi

**Comment by alantrrs** [comment]
Hi I think your are talking about the QOpenTLD, you should contact Paul Naderp on the OpenTLD forum.
